### ISSUE TITLE
varlink URL standard is gone

### ISSUE THREAD

**Issue by tyll** [varlink/python#25]
The README points to https://github.com/varlink/documentation/wiki#address for the varlink URL standard. This points only the homepage. The homepage does not seem to contain details about the URL standard.  https://github.com/varlink/varlink.github.io/wiki/Home/f6dc2d249d848a4b18a88b6c2caecec6621968f2#address seems to be the old content and it mentions `exec:...` addresses but they are not mentioned here in the tests.

Does python-varlink support implementing `exec:..` varlink services?

**Comment by haraldh** [comment]
Ok, will fix it to point to https://varlink.org/#address

Only `tcp:` and `unix:` are currently implemented.

`exec:` and `ssh:` are mostly for the `varlink-cli` tool or internally for a `varlink` system proxy daemon. They can be implemented also with the library.

See the `C` or `rust` implementations for more sophisticated usage of `exec:` and `ssh:`
