### ISSUE TITLE
How do I list exposed methods? `python -m varlink.cli help` doesn't work

### ISSUE THREAD

**Issue by TomasTomecek** [varlink/python#4]
Unfortunately, there is no cli module as described in the readme:
```
$ python3 -m varlink.cli help unix:/run/io.projectatomic.podman
/bin/python3: No module named varlink.cli

$ rpm -q python3-varlink
python3-varlink-22-1.fc29.noarch

$ ll /run/io.projectatomic.podman
srw-rw-rw-. 1 root root 0 May 10 10:11 /run/io.projectatomic.podman
```

**Comment by haraldh** [comment]
have to update fedora.. sorry, that is new... use pip for now

**Comment by haraldh** [comment]
or use /usr/bin/varlink from libvarlink-utils

**Comment by haraldh** [comment]
see also:
https://github.com/varlink/python/commit/4059fc0d3239d6fb9ddcc04206a80b631778bfe1#diff-04c6e90faac2675aa89e2176d2eec7d8R39

or the old README version... for version 22

https://github.com/varlink/python/blob/04075a4df9516963f88775ab416b6d903f98fd05/README.md

**Comment by TomasTomecek** [comment]
will do, thank you!

**Comment by haraldh** [comment]
python update with the cli: https://bodhi.fedoraproject.org/updates/python-varlink-25-1.fc28
please test and leave karma
